# Generated by Django 4.2.4 on 2023-11-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo_id', models.CharField(max_length=100)),
                ('ruta1_id', models.CharField(max_length=100)),
                ('ruta2_id', models.CharField(max_length=100)),
                ('ruta3_id', models.CharField(max_length=100)),
                ('distancia1', models.IntegerField()),
                ('distancia2', models.IntegerField()),
                ('distancia3', models.IntegerField()),
                ('duracion1', models.IntegerField()),
                ('duracion2', models.IntegerField()),
                ('duracion3', models.IntegerField()),
                ('consumo_ajustado1', models.IntegerField()),
                ('consumo_ajustado2', models.IntegerField()),
                ('consumo_ajustado3', models.IntegerField()),
                ('porcentaje_bateria1', models.IntegerField()),
                ('porcentaje_bateria2', models.IntegerField()),
                ('porcentaje_bateria3', models.IntegerField()),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
            ],
        ),
    ]
