# Generated by Django 4.2.4 on 2023-09-18 18:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_chargepoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradmin',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
