# Generated by Django 4.2.4 on 2023-09-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_useradmin_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='latitude_destination',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='latitude_origin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='longitude_destination',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='longitude_origin',
            field=models.FloatField(),
        ),
    ]
