# Generated by Django 4.2.4 on 2023-09-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_chargepoint_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='battery_percentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
