# Generated by Django 4.2.4 on 2023-09-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_route_battery_percentage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectricVehicle",
            fields=[
                ("vehicle_id", models.AutoField(primary_key=True, serialize=False)),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                (
                    "battery_capacity_kwh",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("range_kilometers", models.PositiveIntegerField()),
                (
                    "charging_time_hours",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("created_at_electricVehicle", models.DateTimeField(auto_now_add=True)),
                ("updated_at_electricVehicle", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
