# Generated by Django 4.2.4 on 2023-09-20 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0009_chargepoint_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricvehicle',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='user',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useradmin',
            name='charge_point',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='pages.chargepoint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useradmin',
            name='electric_vehicle',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='pages.electricvehicle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useradmin',
            name='route',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='pages.route'),
            preserve_default=False,
        ),
    ]
