# Generated by Django 4.2.4 on 2023-10-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_chargepoint_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
