# Generated by Django 4.2.4 on 2023-11-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_chargepoint_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics_consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statistics_id', models.IntegerField()),
                ('Enero', models.IntegerField()),
                ('Febrero', models.IntegerField()),
                ('Marzo', models.IntegerField()),
                ('Abril', models.IntegerField()),
                ('Mayo', models.IntegerField()),
                ('Junio', models.IntegerField()),
                ('Julio', models.IntegerField()),
                ('Agosto', models.IntegerField()),
                ('Septiembre', models.IntegerField()),
                ('Octubre', models.IntegerField()),
                ('Noviembre', models.IntegerField()),
                ('Diciembre', models.IntegerField()),
                ('consumo_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistics_percentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statistics_id', models.IntegerField()),
                ('Enero', models.IntegerField()),
                ('Febrero', models.IntegerField()),
                ('Marzo', models.IntegerField()),
                ('Abril', models.IntegerField()),
                ('Mayo', models.IntegerField()),
                ('Junio', models.IntegerField()),
                ('Julio', models.IntegerField()),
                ('Agosto', models.IntegerField()),
                ('Septiembre', models.IntegerField()),
                ('Octubre', models.IntegerField()),
                ('Noviembre', models.IntegerField()),
                ('Diciembre', models.IntegerField()),
                ('porcentaje_consumido', models.IntegerField()),
                ('carga_restante', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo_id', models.CharField(max_length=100)),
                ('ruta_id', models.CharField(max_length=100)),
                ('distancia', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('consumo_ajustado', models.IntegerField()),
                ('porcentaje_bateria', models.IntegerField()),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('Statistics_id', models.IntegerField()),
                ('fecha', models.DateField()),
                ('Enero', models.IntegerField()),
                ('Febrero', models.IntegerField()),
                ('Marzo', models.IntegerField()),
                ('Abril', models.IntegerField()),
                ('Mayo', models.IntegerField()),
                ('Junio', models.IntegerField()),
                ('Julio', models.IntegerField()),
                ('Agosto', models.IntegerField()),
                ('Septiembre', models.IntegerField()),
                ('Octubre', models.IntegerField()),
                ('Noviembre', models.IntegerField()),
                ('Diciembre', models.IntegerField()),
                ('porcentaje_consumido', models.IntegerField()),
                ('carga_restante', models.IntegerField()),
                ('consumo_total', models.IntegerField()),
            ],
        ),
    ]
