# Generated by Django 4.2.4 on 2023-09-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('distance', models.IntegerField()),
                ('time', models.IntegerField()),
                ('latitude_origin', models.IntegerField()),
                ('latitude_destination', models.IntegerField()),
                ('longitude_origin', models.IntegerField()),
                ('longitude_destination', models.IntegerField()),
                ('created_at_route', models.DateTimeField(auto_now_add=True)),
                ('updated_at_route', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
