# Generated by Django 4.2.4 on 2023-09-18 18:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_point', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at_point', models.DateTimeField(auto_now_add=True)),
                ('updated_at_point', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('distance', models.IntegerField()),
                ('time', models.IntegerField()),
                ('latitude_origin', models.IntegerField()),
                ('latitude_destination', models.IntegerField()),
                ('longitude_origin', models.IntegerField()),
                ('longitude_destination', models.IntegerField()),
                ('created_at_route', models.DateTimeField(auto_now_add=True)),
                ('updated_at_route', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('created_at_user', models.DateTimeField(auto_now=True)),
                ('updated_at_user', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
