# Generated by Django 4.2.4 on 2023-09-19 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_UserAdmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargePoint',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
